### ISSUE TITLE
How to solve the problem of Chinese garbled

### ISSUE THREAD

**Issue by vtkom** [song940/node-bluetooth#11]
����3s
bluetooth1.1.js:19 Found: 1C:CD:E5:8C:05:88 with name ����3s1
bluetooth1.1.js:18 RG-BLE-22
bluetooth1.1.js:19 Found: 1E:03:E0:81:39:BB with name RG-BLE-222
events.js:86 finished

**Comment by vtkom** [comment]
How to solve the problem of Chinese scrambled code

**Comment by song940** [comment]
You may need charsets encoding conversion like [iconv-lite](https://www.npmjs.com/package/iconv-lite) .
