### ISSUE TITLE
connectivity problems

### ISSUE THREAD

**Issue by tzvetelin-vassilev** [song940/node-bluetooth#16]
I have tested om Mac with High Sierra. 

When bt connection is lost error event is emitted with message "The connection has been closed", but never emitted closed event. 

Also have problems with inquire() method. It freezes my app and the only way is to kill the process. There are not any reported errors. Anyhow inquire should be async.

**Comment by tzvetelin-vassilev** [comment]
On Connection.prototype.close = function(address, callback); also small bug is found.

----------
  if (typeof address === 'function') {
    callback = address;
    address = null;
  }
  try {
    this.port.close(address);
----------

When address is null port.close throws error.

**Comment by song940** [comment]
I fixed that at [1.2.2](https://github.com/song940/node-bluetooth/commit/438e893d9c7f6aec1622ed5fbc890f7dae9c6d88) .

**Comment by tzvetelin-vassilev** [comment]
But problems related with inquiry and close event are available in 1.2.2. It still is not emitted and inquiry never completes (found and finished events never fired) and app should be killed.

**Comment by rdgrsrl** [comment]
Actually I can confrim that `new bluetooth.DeviceINQ().inquire()` should be async. Why are we subscribing callbacks if the subscriber method is synchronous?
