### ISSUE TITLE
Connecting to a device with a pin pairing

### ISSUE THREAD

**Issue by DarkDestry** [song940/node-bluetooth#36]
Im connecting to a HC-06 device that requires a pin to pair. 

Before manually pairing, `Error: Cannot Connect` is thrown
After manually pairing, works like a charm.

Is there any API to assist in pin pairing?

**Comment by abhinavjuneja** [comment]
@DarkDestry Were you able to find a way to connect without manually pairing?

**Comment by DarkDestry** [comment]
Sadly no
