### ISSUE TITLE
Receiving

### ISSUE THREAD

**Issue by wayofthefuture** [song940/node-bluetooth#5]
This is a really nice library. I notice in the example you've sent data to the bluetooth device. Do you know if it is possible to receive data FROM the bluetooth device?? Thanks!

**Comment by jeanlescure** [comment]
+1 to @wayofthefuture's question, does the library allow receiving data?

**Comment by song940** [comment]
example https://github.com/song940/node-bluetooth/blob/master/example/index.js#L22
