### ISSUE TITLE
NULLing out io_service_t. Error: Cannot connect

### ISSUE THREAD

**Issue by wbhob** [song940/node-bluetooth#8]
Got this error trying to connect to an iPhone.

```
2017-07-25 20:24:39.900 node[50282:2060186] [establishKernelConnection] Received an error from IOServiceOpen() - 0xe00002c7.  NULLing out io_service_t.
Error: Cannot connect
```

Here is my code.

```ts
    device
        .on('finished', console.log.bind(console, 'finished'))
        .on('found', function found(address, name) {

            console.log('Found: ' + address + ' with name ' + name);

            // find serial port channel
            device.findSerialPortChannel(address, (channel) => {
                console.log('Found RFCOMM channel for serial port on %s: ', name, channel);

                // make bluetooth connect to remote device
                bluetooth.connect(address, channel, (err, connection) => {
                    if (err) return console.error(err);

                    connection.on('data', (buffer) => {
                        console.log('received message:', buffer.toString());
                    });

                    connection.write(new Buffer('Hello!', 'utf-8'), () => {
                        console.log('wrote');
                    });
                });

            });

        }).inquire();
```

**Comment by maccelerated** [comment]
This would happen to me anytime I sent data to an RPi.

**Comment by peterpoliwoda** [comment]
Anybody figured out yet how to debug this IOServiceOpen problem? I'm getting stuck on connection. The MacBook Air laptop is actually clearly starting to connect to the device in the Bluetooth menu so something is happening, and it stays connected. 

![image](https://user-images.githubusercontent.com/14016749/66963541-d6f41c80-f06b-11e9-802b-904ee0ff8516.png)

Can't seem to get the actual connection though.

Problem is, the node code is returning connection errors.

```
2019-10-16 23:11:45.177 node[2843:91060] [establishKernelConnection] Received an error from IOServiceOpen() - 0xe00002c7.  NULLing out io_service_t.
[Error: Cannot connect]

```

Don't really see a way to get to an existing connection using this somehow and just give it some data to send over.

**Comment by Haugf** [comment]
Did anyone ever make it pass this error?

I'm currently trying to connect the example app to my iPhone and I found it but I am getting this error.

I am also getting a depreciation error for a buffer() command somewhere in the code.

**Comment by wbhob** [comment]
no longer working with this. closing

**Comment by peterpoliwoda** [comment]
OK, not great. Is there an alternative to this module I could use instead?

**Comment by Haugf** [comment]
For BLE? I have been looking into noble, there is also chrome's built int bluetooth navigator module but I haven't been able to get it to work yet
